travis:
  secure:
    BINSTAR_TOKEN: BmNnk7aAyznZfeSCCyVWVymOsiIBLX3buZe6HeMmlyF6SsKSV7d0L1y7sK+2QoQavLvhiIxxMAvGawqdInYitHkwPm//XZeb/y7790TTXJYJ/WXMxDJRTfnIC/yxWjAcINJxcH9wAFrygY972s3PkR6H40KrJpVHiXbwfk7DbkWhTqAkRRaC5DTga3DTRfws1sX5Dky8yvslW+fT2NUvUo3kn6N3rOkSzIqZOGvAuM0FXTKKjU/tjttvUNL8IWrTfj7uqQyKa0QNfKlwkXbfKmqUnX+Kz37HzRmF8FE71MCXreWoNjq4XIDi1SjS3ng9/C+6ragbl2M5W89VTiynDyUvldQMeoOLkZZt6S+m9E6XpROC+ctHx7col1rCA2ZvwRMq3Uku2WvyN/s6jfIXxcom4JvdMKw8JMvsyD4dAi8QcUTpK7exJbUqteZh8m3mZDritap5+n6MhMv0TfV4VN9MjAPhZCavOhzxiyK2kPlkbTcxORxAJwXun+yD3eG91xRrzu0/YkpBpt+/4YEKunS50ArCtQGVQ09C2Ii7HMp/tz3G4V1TTWLB1aP+STxMqrMi1hG3PoDr/EL51JokXhe+obpGpvY0yRgssKlrq9C/KW6vP3PmFZ8s56ilnqNLnGD546Cu+DQfAgpCig7YYdPIgXmBjnjsPglaJYVWa5E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
